apiVersion: v1
kind: Service
metadata:
  name: bd-web-service
spec:
  selector:
    app: bd-web
  ports:
  - protocol: "TCP"
    port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bd-web
spec:
  selector:
    matchLabels:
      app: bd-web
  replicas: 1
  template:
    metadata:
      name: bl-web-app
      labels:
        app: bd-web
    spec:
      containers:
      - name: bd-web
        image: hub.osrsbotdetector.com/bot-detector/bd-web:production
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: regcred