version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn src.core.server:app --host 0.0.0.0 --reload --reload-include src/*
    container_name: bd-web
    volumes:
      - ./src:/project/src:rw
    ports:
      - 8000:8000
    networks:
      - botdetector-network

networks:
  botdetector-network: