apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bd-prd-web-ingress
  namespace: default
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: bd-prd-web-service
            port:
              number: 8000
        path: /web(/|$)(.*)
        pathType: Prefix