apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bd-prd-web-ingress
  namespace: default
spec:
  ingressClassName: nginx
  rules:
    - host: osrsbotdetector.com
      http:
        paths:
          - path: /web(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: bd-prd-web-service
                port:
                  number: 8000
