apiVersion: apps/v1
kind: Deployment
metadata:
  name: bd-web-dev
spec:
  selector:
    matchLabels:
      app: bd-web-dev
  replicas: 1
  template:
    metadata:
      name: bl-web-dev-app
      labels:
        app: bd-web-dev
    spec:
      containers:
      - name: bd-web-dev
        image: hub.osrsbotdetector.com/bot-detector/bd-web:development
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
      imagePullSecrets:
      - name: regcred