apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bd-dvp-web-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: bd-dvp-web-service
                port:
                  number: 8001
            path: /webdev(/|$)(.*)
            pathType: Prefix
