api:
  botDetector: http://api:5000
  runeLite: https://api.runelite.net/runelite/pluginhub
data:
  patreons:
    StarterBotHunter:
      - shaGGyTZ 
      - Attilatheguy 
      - mciurlionis 
      - cykaking187 
      - Claudio Dekker 
      - JMoney 
      - Not Goode 
      - Hach 
      - Heklek 
      - Jair 
      - Dennozs 
      - grimsli 
      - Poltergeist 
      - Toastface5 
      - samurai_pr 
      - Springstof 
      - LadyAleksandra 
      - 3Pills 
      - Gertoni Macaroni 
      - Kryllo 
      - RiverRogue 
      - Basti 
      - Infernus 
      - Winning 
      - Hairyngross 
      - Fazel 
      - Jules 
      - Nechtmarrie 
      - Anthony Perez 
      - Anon4777 
      - schulz 
      - iliketostayanonymous 
      - breakthetargets 
      - Nostalgia 
      - Darkpi 
      - Thor 
      - Sasha 
      - val 
      - Caboose700 
      - KuhlGuy 
      - FRED 
      - AgelessOverkill 
      - Caldo dpollo 
      - No Ego 
      - Daniël Roek 
      - MyCrowSoft 
      - Faremir  
      - Beasst  
      - Billy Hunt 
      - Nicholas Earley 
      - Joe Stoica 
      - Tez 
      - Dawnsnite 
      - MrFoxyCracker 
      - acklord 
      - logan10144 
      - fitchett 
      - 7 7 mafia 
      - Jax 
      - Born2Grind 
      - Core 
      - Oondin 
      - Damply 
      - carpetcleaner 
      - tylersandman 
      - Jojy 
      - Lag 
      - Pyrotic 
      - ify 
      - pxjx 
      - Icarus 
      - Hotsaucesam 
      - LookingForPants 
      - Sentry 
      - Oosterbuur
    BronzeBotHunter:
      - Lexiii223 
      - Zirhaze 
      - Lisa Leese (She/They) 
      - Arcane 
      - Seatball Mub 
      - rasmus godske 
      - Cortunix 
      - Beeeooop 
      - louis 
      - Vis 
      - oBIGRON 
      - Amon Havers 
      - Posti 
      - Foxo 
      - sarunas knabikas 
      - Hex
    SteelBotHunter: 
      - Sophlin 
      - SeltzerBro 
      - RoopeK 
      - Richard Andrew
    MithrilBotHunter: 
      - Gottfrid 
      - § Rambo 
      - Ratteo 
      - someranger 
      - 117 
      - PigeonNugget
    AdamantBotHunter: 
      - Sallysal 
      - Rhikalika
    RuneBotHunter: 
    DragonBotHunter: 
      - DevinDog
    